# Generated by Django 6.0.7 on 2026-08-04 13:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='description',
            new_name='descriptions',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='type',
            new_name='transaction_type',
        ),
        migrations.RemoveField(
            model_name='category',
            name='type',
        ),
        migrations.AddField(
            model_name='category',
            name='category_type',
            field=models.CharField(choices=[('INCOME', 'درآمد'), ('EXPENSE', 'هزینه')], default='Income', max_length=12, verbose_name='نوع دسته بندی'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='delete_item_logs', to=settings.AUTH_USER_MODEL, verbose_name='کاربر حذف\u200cکننده'),
        ),
    ]
