# Generated by Django 4.2.30 on 2026-08-28 14:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_rename_description_transaction_descriptions_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='descriptions',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='category',
            name='category_type',
            field=models.CharField(choices=[('INCOME', 'درآمد'), ('EXPENSE', 'هزینه')], max_length=12, verbose_name='نوع دسته بندی'),
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delete_item_logs', to=settings.AUTH_USER_MODEL, verbose_name='کاربر حذف\u200cکننده'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
